const data = [
  {
    id: 0,
    seminar: 'Yearly ECO Seminar',
    test: 'EMS ყოველწლიური სემინარი',
    date: '2020.05.19',
    registration: 'true',
    registered: 'false',
    schedule: [
      {
        date: '2020.05.19',
        hour: '12:00',
        teacher: ' ტარიელ თითირაშვილი',
      },
      {
        date: '2020.05.19',
        hour: '14:00',
        teacher: 'ტარიელ თითირაშვილი',
      },
    ],
  },
  {
    id: 1,
    seminar: 'Yearly ECO Seminar',
    test: 'EMS ყოველწლიური სემინარი',
    date: '2020.05.20',
    registration: 'true',
    registered: 'false',
    schedule: [
      {
        date: '2020.05.19',
        hour: '12:00',
        teacher: ' ტარიელ თითირაშვილი',
      },
    ],
  },
  {
    id: 2,
    seminar: 'AML Training',
    test: 'ფულის გათეთრების აღკვეთა (AML)',
    date: '2020.07.16',
    registration: 'true',
    registered: 'false',
  },
  {
    id: 3,
    seminar: 'Yearly ECO Seminar',
    test: 'EMS ყოველწლიური სემინარი',
    date: '2020.07.21',
    registration: 'true',
    registered: 'false',
    schedule: [],
  },
  {
    id: 4,
    seminar: 'Yearly ECO Seminar',
    test: 'EMS ყოველწლიური სემინარი',
    date: '2020.07.21',
    registration: 'true',
    registered: 'false',
    schedule: [],
  },
  {
    id: 5,
    seminar: 'Operational Risk and Information Security',
    test: 'საოპერაციო რისკები და ინფორმაციის უსაფრთხოება',
    date: '2020.07.28',
    registration: 'true',
    registered: 'false',
    schedule: [],
  },
  {
    id: 6,
    seminar: 'Operational Risk and Information Security',
    test: 'საოპერაციო რისკები და ინფორმაციის უსაფრთხოება',
    date: '2020.07.30',
    registration: 'true',
    registered: 'false',
    schedule: [],
  },
  {
    id: 7,
    seminar: 'Operational Risk and Information Security',
    test: 'საოპერაციო რისკები და ინფორმაციის უსაფრთხოება',
    date: '2020.07.31',
    registration: 'true',
    registered: 'false',
    schedule: [],
  },
  {
    id: 8,
    seminar: 'Operational Risk and Information Security',
    test: 'საოპერაციო რისკები და ინფორმაციის უსაფრთხოება',
    date: '2020.08.17',
    registration: 'true',
    registered: 'false',
    schedule: [],
  },
  {
    id: 9,
    seminar: 'Operational Risk and Information Security',
    test: 'საოპერაციო რისკები და ინფორმაციის უსაფრთხოება',
    date: '2020.08.19',
    registration: 'true',
    registered: 'false',
    schedule: [],
  },
  {
    id: 10,
    seminar: 'Operational Risk and Information Security',
    test: 'საოპერაციო რისკები და ინფორმაციის უსაფრთხოება',
    date: '2020.08.21',
    registration: 'true',
    registered: 'false',
    schedule: [],
  },
  {
    id: 11,
    seminar: 'Operational Risk and Information Security',
    test: 'საოპერაციო რისკები და ინფორმაციის უსაფრთხოება',
    date: '2020.08.24',
    registration: 'true',
    registered: 'false',
    schedule: [],
  },
  {
    id: 12,
    seminar: 'Operational Risk and Information Security',
    test: 'საოპერაციო რისკები და ინფორმაციის უსაფრთხოება',
    date: '2020.08.26',
    registration: 'true',
    registered: 'false',
    schedule: [],
  },
  {
    id: 13,
    seminar: 'Operational Risk and Information Security',
    test: 'საოპერაციო რისკები და ინფორმაციის უსაფრთხოება',
    date: '2020.08.27',
    registration: 'true',
    registered: 'false',
    schedule: [],
  },
  {
    id: 14,
    seminar: 'AML Training',
    test: 'ფულის გათეთრების აღკვეთა (AML)',
    date: '2020.08.12',
    registration: 'true',
    registered: 'false',
    schedule: [],
  },
  {
    id: 15,
    seminar: 'Operational Risk and Information security',
    test: 'საოპერაციო რისკები და ინფორმაციის უსაფრთხოება',
    date: '2020.10.13',
    registration: 'true',
    registered: 'false',
    schedule: [],
  },
];

export default data;
