export const GET_TRAININGS_FROM_API = "_GET_TRAININGS_FROM_API_";
export const GET_TESTS_FROM_API = "__GET_TESTS_FROM_API___";
export const GET_PASSED_TRAININGS_FROM_API = "__GET_PASSED_TRAININGS_FROM_API____";
export const GET_PASSED_USER_INFO_FROM_API = "GET_PASSED_USER_INFO_FROM_API____";
export const ADMIN = "ADMIN"
export const SET_USER_DATA_DETAILS = "___SET___USER___DATA___DETAILS"